#!/bin/sh
#
# @license   http://www.gnu.org/licenses/gpl.html GPL Version 3
# @author    Simon Baur <sbausis@gmx.net>
# @copyright Copyright (c) 2015 Simon Baur
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

if [ "$1" = "purge" ]; then

	FOLDER="/var/cache/openmediavault"
	FILES="cached_module_nodes.json cached_module_override_nodes.json cached_module_override_panels.json cached_module_panels.json"
	for FILE in ${FILES}; do
		[ -f "${FOLDER}/${FILE}" ] && /bin/rm "${FOLDER}/${FILE}"
	done

fi

#DEBHELPER#

exit 0
