#!/bin/sh
#
# @license   http://www.gnu.org/licenses/gpl.html GPL Version 3
# @author    Simon Baur <sbausis@gmx.net>
# @copyright Copyright (c) 2015 Simon Baur
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

if [ "$1" = "purge" ]; then

    if [ -f /var/cache/cached_admin_nodes.list ]; then
        /bin/rm /var/cache/cached_admin_nodes.list
    fi

    if [ -f /var/cache/cached_admin_panels.list ]; then
        /bin/rm /var/cache/cached_admin_panels.list
    fi


    if [ -f /var/cache/cached_user_nodes.list ]; then
        /bin/rm /var/cache/cached_user_nodes.list
    fi

    if [ -f /var/cache/cached_user_panels.list ]; then
        /bin/rm /var/cache/cached_user_panels.list
    fi


    if [ -f /var/cache/cached_public_nodes.list ]; then
        /bin/rm /var/cache/cached_public_nodes.list
    fi

    if [ -f /var/cache/cached_public_panels.list ]; then
        /bin/rm /var/cache/cached_public_panels.list
    fi

fi

#DEBHELPER#

exit 0
